FROM java:8-alpine

ADD target/*.jar 

EXPOSE 8282

ENTRYPOINT ["java","-Dserver.port=8282","-Dspring.profiles.active=aws","-Djava.security.egd=file:/dev/.urandom","-jar","/gehc-ai-datacatalog-1.0-SNAPSHOT.jar"]