### AWS
spring:
  datasource:
    url: ${spring_datasource_url:jdbc:mysql://dd13e7t1i438cg0.cum7uudlheyn.us-east-1.rds.amazonaws.com:3306/lfdb}
    username: ${spring_datatsource_username:dbadmin123}
    password: ${spring_datasource_password:d165376b867}
  data:
    rest.base-path: /api/v1/dataCatalog
  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: false
experiment:
  targetData:
    gtMaskLocation: https://gehc-sandbox-cos-dev.s3.amazonaws.com/object/
    imgLocation: https://gehc-sandbox-cos-dev.s3.amazonaws.com/object/
    locationType: s3
uom.user.me.url: ${uom_api_gateway_url:https://6zpi3igymc.execute-api.us-east-1.amazonaws.com/prdge_idam_uomapi}/v1/user/me?level.value=2
dev:
  mode: false
  orgId: null
#flyway:
#  enabled: ${flyway_enabled:false}
#  schemas: lfdb
#  baselineOnMigrate: true
#  validateOnMigrate: false
#  url: ${spring_datasource_url:jdbc:mysql://localhost:3306/lfdb?useLegacyDatetimeCode=false&serverTimezone=PST}
#  user: ${spring_datatsource_username:root}
#  password: ${spring_datasource_password:root}
---
##Local
## Use -Dspring.profiles.active=local as part of the JVM arguments when running locally
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/lfdb?useLegacyDatetimeCode=false&serverTimezone=PST
    username: root
    password: root
