##Local
#spring.datasource.url = jdbc:mysql://localhost:3306/deeplearning?useLegacyDatetimeCode=false&serverTimezone=PST
#spring.datasource.username = root
#spring.datasource.password = root
#spring.data.rest.base-path=/api/v1/dataCatalog
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#experiment.targetData.gtMaskLocation = s3://gehc-data-repo-main/imaging/ct/lungData/LungCT_LIDC_LS/annot1
#experiment.targetData.imgLocation = https://s3.amazonaws.com/gehc-sandbox-cos-dev/upload/vto11exhd2/
#experiment.targetData.locationType = s3


##AWS
#spring.datasource.url = jdbc:mysql://localhost:3307/learningfactory
#Need to remove above
spring.datasource.url = jdbc:mysql://learningfactory.cum7uudlheyn.us-east-1.rds.amazonaws.com:3306/learningfactory
spring.datasource.username = lfuser
spring.datasource.password = FeelGood?
spring.data.rest.base-path=/api/v1/dataCatalog
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
experiment.targetData.gtMaskLocation = s3://gehc-data-repo-main/imaging/ct/lungData/LungCT_LIDC_LS/annot1
experiment.targetData.imgLocation = https://s3.amazonaws.com/gehc-sandbox-cos-dev/upload/vto11exhd2/
experiment.targetData.locationType = s3


