#Local
#spring.datasource.url = jdbc:mysql://localhost:3306/deeplearning
#spring.datasource.username = root
#spring.datasource.password = root

#AWS
spring.datasource.url = jdbc:mysql://localhost:7200/deeplearning
spring.datasource.username = admin
spring.datasource.password = ashis123